### ISSUE TITLE
Blog posts not showing up on my profile 

### ISSUE THREAD

**Issue by 0xecho** [diffblog/diff.blog#1]

**Comment by TomCasavant** [comment]
Have you figured this out? I ran into a similar issue, where my blog posts weren't being found and the fix ended up being removing the newline right before the 
`<?xml version="1.0" encoding="utf-8"?>`
line at the beginning of the rss feed.

**Comment by hackerkid** [comment]
@maurovanetti Looks like the post does show up on your profile.

@0xecho Your feed URL in your diff.blog profile seems to be 404ing. Can you reopen the issue with more details if the issue persists even after updating the URL? Thanks!

**Comment by hackerkid** [comment]
Also created https://github.com/diffblog/diff.blog/issues/13 to include more debugging information in the UI.
