### ISSUE TITLE
How to add tags/topics to my blog posts?

### ISSUE THREAD

**Issue by AnshumanTripathi** [diffblog/diff.blog#3]
[My blog post ](https://diff.blog/post/terraform-basics-134301/) is not showing any tags/topics even though the [actual post has tags set](https://www.anshumantripathi.com/blog/terraform-basics/). Are there any specific metadata values I can add to my blog post?

**Comment by nathiss** [comment]
Any luck with figuring it out?

**Comment by heitorPB** [comment]
Did you figure it out? @hackerkid do you have this documented somewhere?

**Comment by heitorPB** [comment]
@AnshumanTripathi @nathiss I figured it out: diff.blog works with your site rss/atom feed files. You need to properly add the tags in there.

For Atom 1.0, you need to add `<category term="the-tag-you-want"/>` to each `<entry>` element. See https://validator.w3.org/feed/docs/atom.html#recommendedFeedElements for details.

For RSS 2.0, the syntax ix `<category>The tag you want</category>`. See https://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt for details.

My posts now are all tagged: https://diff.blog/heitorPB/

**Comment by hackerkid** [comment]
@heitorPB Yeah. That is correct. I am actually considering open sourcing the source code. This issue seems to be clearly something you could have figured out yourself if the code was here.

**Comment by heitorPB** [comment]
@hackerkid totally! I really support the open source idea :D

Meanwhile, what about adding a FAQ or Docs page with these questions?

**Comment by hackerkid** [comment]
@heitorPB diff.blog is now OpenSource!

There is a FAQ page at [here](https://github.com/diffblog/diff.blog/blob/master/templates/faq.html) if you want to create a pull request! :)
